### ISSUE TITLE
The super class vtable is out of date. Make sure your kext has been built against the correct headers.

### ISSUE THREAD

**Issue by jscipione** [DigitalExegete/CTProdikeysMac#1]
$ sudo kextutil -v 4 /System/Library/Extensions/CTProdikeysMac.kext
Kext library architecture set to x86_64.
Defaulting to kernel file '/System/Library/Kernels/kernel'
Kext library recording diagnostics for: validation authentication dependencies warnings.
Reading loaded kext info from kernel.
Reading loaded kext info from kernel.
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fc431c4ec20 [0x7fffa0e3e8e0]> { URL = "file:///System/Library/Extensions/CTProdikeysMac.kext/", ID = "com.treblottomusictech.CTProdikeysMac" }
Code Signing Failure: code signature is invalid
/System/Library/Extensions/CTProdikeysMac.kext appears to be loadable (not including linkage for on-disk libraries).
Reading loaded kext info from kernel.
Loading /System/Library/Extensions/CTProdikeysMac.kext.
Reading load info for 16 kexts.
Reading loaded kext info from kernel.
Disabling KextAudit: SIP is off
KextAudit initialized: audit=F
Adding /System/Library/Extensions/CTProdikeysMac.kext to mkext.
/System/Library/Extensions/CTProdikeysMac.kext added 64000-byte noncompressed executable to mkext.
Created mkext for architecture x86_64 containing 1 kexts.
Loading /System/Library/Extensions/CTProdikeysMac.kext.
(kernel) Received request from user space to load kext com.treblottomusictech.CTProdikeysMac.
(kernel) Loading kext com.treblottomusictech.CTProdikeysMac.
(kernel) Allocated link buffer for kext com.treblottomusictech.CTProdikeysMac at 0xffffff7f93459000 (20480 bytes).
(kernel) kxld[com.treblottomusictech.CTProdikeysMac]: The super class vtable '__ZTV18IOUSBHostHIDDevice' for vtable '__ZTV19TMMTCTProdikeysMIDI' is out of date. Make sure your kext has been built against the correct headers.
(kernel) Can't load kext com.treblottomusictech.CTProdikeysMac - link failed.
(kernel) Failed to load executable for kext com.treblottomusictech.CTProdikeysMac.
(kernel) Kext com.treblottomusictech.CTProdikeysMac failed to load (0xdc008016).
(kernel) Failed to load kext com.treblottomusictech.CTProdikeysMac (error 0xdc008016).
(kernel) Kext com.treblottomusictech.CTProdikeysMac removing all personalities naming it from the IOCatalogue.
Failed to load /System/Library/Extensions/CTProdikeysMac.kext - (libkern/kext) link error.
Failed to load /System/Library/Extensions/CTProdikeysMac.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).

**Comment by jscipione** [comment]
Just had to update my deployment target from 10.12 to 10.13 to fix this error

**Comment by DigitalExegete** [comment]
Cool—also, I’m building/designing this for Mojave, but glad to see that it worked. The MIDI driver project is missing a lot of files. I’ll be sure to commit those this evening.

**Comment by jscipione** [comment]
Hey can you commit the missing midi driver files I got this to build but didn't get the midi part to connect in MIDI Studio.

**Comment by DigitalExegete** [comment]
Yup--give me a few minutes. Sorry about that!

**Comment by DigitalExegete** [comment]
hey @jscipione -- the files are all there, I just built in on my machine, it *should* work on yours, too.  Let me know if you have any issues.
